// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://getknntqapnpnsxrzhkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdldGtubnRxYXBucG5zeHJ6aGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTA2ODIsImV4cCI6MjA2NzEyNjY4Mn0.GitniDVrBDH4k7xybH0dwaEYpbqMeQG3i-3toSreWjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});